### PR TITLE
add missing people (Navid, Richard)

### PR DESCRIPTION
**Pull request by ComFreek**

### CODE REVIEW

**Comment by tkw1536** [comment]
LGTM

**Comment by kohlhase** [comment]
I think there is one more change you have to do for this to work.

**Comment by tkw1536** [comment]
Nope, this is working, see https://kwarc.github.io/bibs/nroux/ and https://kwarc.github.io/bibs/rmarcus/. Just took some time to build.

**Comment by ComFreek** [comment]
@tkw1536 But the first heading lists abbreviated names instead of full names. I am wondering where, say, "Michael Kohlhase" on https://kwarc.github.io/bibs/mkohlhase/ is coming from.

**Comment by tkw1536** [comment]
It's probably the first author of the first entry on the .bib that contains the nroux tag.

**Pull request merged**
